apiVersion: v2
name: users-api
description: Users API deployment
type: application
version: 0.1.0
appVersion: 0.1.4
sources:
- https://github.com/beantownpub/users-api

dependencies:
  - name: psql
    version: 0.1.6
    repository: https://beantownpub.github.io/helm/
    condition: database.enabled
    namespace: database
